version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: ecommerce-postgres
    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_USER: prasad
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U prasad -d ecommerce"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Order Service (Port 8081)
  order-service:
    build: ./order-service
    container_name: order-service
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ecommerce
      SPRING_DATASOURCE_USERNAME: prasad
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  # Inventory Service (Port 8082)  
  inventory-service:
    build: ./inventory-service
    container_name: inventory-service
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ecommerce
      SPRING_DATASOURCE_USERNAME: prasad
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
	
	# Payment Service (Port 8083)
	payment-service:              
	    build: ./payment-service
	    ports: - "8083:8083"
	    environment:
	      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ecommerce
	      SPRING_DATASOURCE_USERNAME: prasad
	      SPRING_DATASOURCE_PASSWORD: root
		  depends_on:
		       postgres:
		         condition: service_healthy
		     restart: unless-stopped

		
	#Delivery Service (Port 8084)
		
	delivery-service:             
		    build: .
		    ports: - "8084:8084"
		    environment:
		      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ecommerce
		      SPRING_DATASOURCE_USERNAME: prasad
		      SPRING_DATASOURCE_PASSWORD: root
			  depends_on:
			       postgres:
			         condition: service_healthy
			     restart: unless-stopped



  # API Gateway (Port 8080)
  gateway-service:
    build: ./gateway-service
    container_name: ecommerce-gateway
    ports:
      - "8080:8080"
    depends_on:
		- order-service
	    - inventory-service
	    - payment-service
	    - delivery-service
    restart: unless-stopped

volumes:
  postgres_data:
